ALTER TABLE fixtures
ADD COLUMN IF NOT EXISTS home_form JSONB,
ADD COLUMN IF NOT EXISTS away_form JSONB,
ADD COLUMN IF NOT EXISTS odds_over_25 TEXT,
ADD COLUMN IF NOT EXISTS odds_under_25 TEXT,
ADD COLUMN IF NOT EXISTS insights_updated_at TIMESTAMPTZ;
